- name: Setup l4 loadbalancing
  block:
    - name: Write nginx config for l4 routing
      ansible.builtin.template:
        src: l4.conf.j2
        dest: /etc/nginx/sites-available/l4.conf
        mode: '0644'
      register: nginx_config_template_output

    - name: Link nginx config to enable
      ansible.builtin.file:
        src: /etc/nginx/sites-available/l4.conf
        dest: /etc/nginx/sites-enabled/l4/l4.conf
        force: true
        state: link
  when: nginx.l4 is defined

