- name: Setup l7 loadbalancing
  block:
    - name: Write nginx config for l7 routing
      ansible.builtin.template:
        src: l7.conf.j2
        dest: /etc/nginx/sites-available/l7.conf
        mode: '0644'

    - name: Link nginx config to enable
      ansible.builtin.file:
        src: /etc/nginx/sites-available/l7.conf
        dest: /etc/nginx/sites-enabled/l7.conf
        force: true
        state: link
  when: nginx.l7 is defined

