- name: Setup local loadbalancing
  block:
    - name: Write nginx config for local routing
      ansible.builtin.template:
        src: local.conf.j2
        dest: /etc/nginx/sites-available/local.conf
        mode: '0644'

    - name: Link nginx config to enable
      ansible.builtin.file:
        src: /etc/nginx/sites-available/local.conf
        dest: /etc/nginx/sites-enabled/l7/local.conf
        force: true
        state: link
  when: nginx.local is defined

