- name: Install & setup nginx
  block:
    - name: Update apt packages
      ansible.builtin.apt:
        cache_valid_time: 3600
        update_cache: true

    - name: Install nginx package
      ansible.builtin.apt:
        name: 
          - nginx
          - nginx-full
        state: present

    - name: Disable default config
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Configure basic nginx settings
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf

    - name: Create l4 folder if not present
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/l4
        state: directory

    - name: Create l7 folder if not present
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/l7
        state: directory

    - name: "Configure l4 routes"
      ansible.builtin.include_tasks:
        file: l4_loadbalancer.yml

    - name: "Configure l7 routes"
      ansible.builtin.include_tasks:
        file: l7_loadbalancer.yml

    - name: "Configure local routes"
      ansible.builtin.include_tasks:
        file: local_loadbalancer.yml

    - name: Restart nginx 
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
      when: nginx_config_template_output.changed 
    
    - name: Start nginx service
      ansible.builtin.systemd_service:
        name: nginx
        state: started
  become: true
