- name: Install & setup haproxy
  block:
    - name: Update apt packages
      ansible.builtin.apt:
        cache_valid_time: 3600
        update_cache: true

    - name: Install nginx package
      ansible.builtin.apt:
        name: 
          - haproxy
        state: present

    - name: Configure basic nginx settings
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf

    - name: Restart nginx 
      ansible.builtin.systemd_service:
        name: haproxy
        state: restarted
    
    - name: Start nginx service
      ansible.builtin.systemd_service:
        name: haproxy
        state: started
  become: true
