- name: Install rancher server 
  ansible.builtin.import_tasks: install_rke2_server.yml
  become: true
  when: '"rancher_server" in group_names' 

- name: Retrieve server token from {{ rancher_server }}
  ansible.builtin.slurp: 
    src: /var/lib/rancher/rke2/server/node-token
  become: true
  delegate_to: "{{ rancher_server }}"
  register: rke_server_token_slurp
  when: '"rancher_agent" in group_names' 

- name: Register server token from {{ rancher_server }}
  ansible.builtin.set_fact: 
    rke_server_token: "{{ rke_server_token_slurp['content'] | b64decode }}"
  when: '"rancher_agent" in group_names' 

- name: Install rancher agent 
  ansible.builtin.import_tasks: install_rke2_agent.yml
  become: true
  when: '"rancher_agent" in group_names' 

- name: Get local rancher user
  ansible.builtin.set_fact:
    rancher_user: "{{ lookup('env', 'USER') }}"
  when: '"rancher_server" in group_names' 

- name: Ensure the .kube directory exists in the user's home
  ansible.builtin.file:
    path: "/home/{{ rancher_user }}/.kube"
    state: directory
    owner: "{{ rancher_user }}"
    group: "{{ rancher_user }}"
  when: '"rancher_server" in group_names' 

- name: Copy rancher settings to user directory
  ansible.builtin.copy:
    src:  /etc/rancher/rke2/rke2.yaml
    dest: "/home/{{ rancher_user }}/.kube/config.yaml" 
    remote_src: true
    owner: "{{ rancher_user }}"
    group: "{{ rancher_user }}"
  when: '"rancher_server" in group_names' 

- name: Setup cluster access on ansible controller
  ansible.builtin.import_tasks: setup_access.yml
  become: true
  when: '"rancher_server" in group_names' 
